SELECT * FROM customer LIMIT 20;

--Q1 . What is the total revenue generated by male / female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

---Q2. Which customers used a discount but still spent more than the average purchhase amount?

SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount)FROM customer)


----Q3. Which are the top 5 products whith the highest average review rating
SELECT item_purchased,AVG(review_rating) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY "Average Product Rating" DESC
LIMIT 5;
---Q4. Compare the avg Purchase Amt b/w Standard and Express Shipping
SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type


---Q5.Do subscriber customer spend more? Compare avg speed & total revenue
--between subsribers & non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS total_customer,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;

---Q6 Which 5 products have the highest percenatge of purchases with discount applied?
SELECT item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END)::numeric / COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-----Q 7 . Segment customers into new ,returning and loyal based on their tital number
------ of previous purchases ,and show the count of each segment
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment, COUNT(*) AS "number of customers"
FROM customer_type
GROUP BY customer_segment;




---Q8. What are the top3 most purchase products within category
-- Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

)



----Q9. Are customers who are repeat buyers (more than 5 purchases) also likely to subscribe?
SELECT subscription_status,
COUNT (customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status



---Q10. REVENUE BY AGE GROUP
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


